-- Oracle 23ai の DROP TABLE IF EXISTS を使う
DROP TABLE IF EXISTS inventory_logs PURGE;
DROP TABLE IF EXISTS order_items PURGE;
DROP TABLE IF EXISTS orders PURGE;
DROP TABLE IF EXISTS customers PURGE;
DROP TABLE IF EXISTS inventory PURGE;
DROP TABLE IF EXISTS products PURGE;
DROP TABLE IF EXISTS categories PURGE;
