CREATE TABLE categories (
  category_id   NUMBER(5)          PRIMARY KEY,
  category_name VARCHAR2(50 CHAR)  NOT NULL
);

CREATE TABLE products (
  product_id    NUMBER(10)         PRIMARY KEY,
  product_name  VARCHAR2(100 CHAR) NOT NULL,
  category_id   NUMBER(5)          NOT NULL REFERENCES categories (category_id),
  price         NUMBER(10)         NOT NULL CHECK (price >= 0),
  is_active     CHAR(1)            DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE inventory (
  product_id     NUMBER(10) PRIMARY KEY REFERENCES products (product_id),
  stock_quantity NUMBER(10) NOT NULL CHECK (stock_quantity >= 0),
  updated_at     DATE       DEFAULT SYSDATE NOT NULL
);

CREATE TABLE customers (
  customer_id   NUMBER(10)         PRIMARY KEY,
  customer_name VARCHAR2(100 CHAR) NOT NULL,
  email         VARCHAR2(255 CHAR) NOT NULL UNIQUE,
  prefecture    VARCHAR2(10 CHAR),
  created_at    DATE               DEFAULT SYSDATE NOT NULL
);

CREATE TABLE orders (
  order_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1006) PRIMARY KEY,
  customer_id  NUMBER(10)   NOT NULL REFERENCES customers (customer_id),
  order_date   DATE         DEFAULT SYSDATE NOT NULL,
  status       VARCHAR2(20) DEFAULT 'PENDING' NOT NULL
               CHECK (status IN ('PENDING', 'PAID', 'SHIPPED', 'CANCELLED')),
  total_amount NUMBER(12)   DEFAULT 0 NOT NULL
);

CREATE TABLE order_items (
  order_id   NUMBER(10) NOT NULL REFERENCES orders (order_id) ON DELETE CASCADE,
  line_no    NUMBER(3)  NOT NULL,
  product_id NUMBER(10) NOT NULL REFERENCES products (product_id),
  quantity   NUMBER(5)  NOT NULL CHECK (quantity > 0),
  unit_price NUMBER(10) NOT NULL CHECK (unit_price >= 0),
  CONSTRAINT pk_order_items PRIMARY KEY (order_id, line_no)
);

CREATE TABLE inventory_logs (
  log_id     NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  product_id NUMBER(10)        NOT NULL REFERENCES products (product_id),
  change_qty NUMBER(10)        NOT NULL,
  reason     VARCHAR2(50 CHAR) NOT NULL,
  logged_at  DATE              DEFAULT SYSDATE NOT NULL
);
